config/routes.rb
Rails.application.routes.draw do
  resources :quickcheckers
  root to: 'pages#home'

  get 'report' => 'pages#report'
  get 'compare' => 'pages#compare'
  get 'quickchecker' => 'quickcheckers#index'

end

app/models/quickchecker.rb
class Quickchecker < ApplicationRecord
    require 'analyser'
    require 'securerandom'

    #Check and call the analysis necessary
    def validate_this(url1,url2,url3)
        @info = []
        @file_nameR = SecureRandom.alphanumeric(10)
        #Checking URLs    
        if (url1 != '')
            getReport(url1,'1') 
        end  
        if (url2 != '')
            getReport(url2,'2') 
        end 
        if (url3 != '')
            getReport(url3,'3')  
        end   
        return @info, @file_nameR
    end    
    
    #Call Tenon.IO to get the analysis result
    # 
    def getReport(url,pos)
    
        
        data = UrlAnalyser.tenon(url)
        info2 = Hash.new
        code = JSON.parse(data)["code"]
        
        puts code
        
        if code == 'success' 
    
            issues = JSON.parse(data)["resultSummary"]["issues"]
            totalIssues = issues["totalIssues"]
            totalErrors = issues["totalErrors"]
            totalWarnings = issues["totalWarnings"]
            
            @info.push(pos)
            @info.push(totalIssues)
            @info.push(totalErrors)
            @info.push(totalWarnings)
    
            resultSet = JSON.parse(data)
           
            for i in 0..totalIssues-1
                standards = "" 
                standards  = resultSet["resultSet"][i]["standards"][0]
                if standards != nil
                    standards = standards.match(/(\d.\d.\d)/)
                else
                    standards =  ["1.1.1"]
                end 
                if resultSet["resultSet"][i]["certainty"] == 100
                    info2[:"error#{i}"] = standards[0]
                else
                    info2[:"warning#{i}"] = standards[0]
                end
            end
            
        #Save the data on fyle 
        
            file_nameR = @file_nameR + '_url'+pos
            open('file/'+file_nameR+'.txt', 'w') do |f|
                    f <<  info2
            end  
        end    
    end   
    
    def countUrl(url2,url3)
        
        count = 1
        if url2 != '' 
            count+=1
        end    
        if url3 != '' 
            count+=1
        end  
        return count
    end    
end

app/controllers/quickcheckers_controller.rb
class QuickcheckersController < ApplicationController
  before_action :set_quickchecker, only: [:show,:destroy]
  protect_from_forgery :except => [:destroy]


  # GET /quickcheckers
  # GET /quickcheckers.json
  def index
    @quickcheckers = Quickchecker.all
  end
  
  # GET /quickcheckers/1
  # GET /quickcheckers/1.json
  def show
    @file_name = @quickchecker.file
  end

  # GET /quickcheckers/new
  def new
    @quickchecker = Quickchecker.new
  end

  # POST /quickcheckers
  # POST /quickcheckers.json
  def create

    @quickchecker = Quickchecker.new(quickchecker_params)
  
    url1 = params[:quickchecker][:url1]
    url2 = params[:quickchecker][:url2]
    url3 = params[:quickchecker][:url3]
    
    url_field = @quickchecker.countUrl(url2,url3)
    
    info = @quickchecker.validate_this(url1,url2,url3)
    
    #Check if one or more websites are valid
    if  url_field == info[0].count/4 
      
      @quickchecker.update(:info =>  info[0])
      @quickchecker.update(:file =>  info[1])
      
      #When the user insert the website3 and leave the website2 empty
      if (url2 == '') && (url3 != '')
          @quickchecker.update(:url2 =>  url3)
      end
     
        respond_to do |format|
          if @quickchecker.save
            format.html { redirect_to @quickchecker, notice: 'Quickchecker was successfully created.' }
            format.json { render :show, status: :created, location: @quickchecker }
          else
            format.html { render :new }
            format.json { render json: @quickchecker.errors, status: :unprocessable_entity }
          end
        end
    else
        redirect_to :back, notice: "Website(s) invalid. Try again, please"
    end  
  end

  # DELETE /quickcheckers/1
  # DELETE /quickcheckers/1.json
  def destroy
    @quickchecker.destroy
    respond_to do |format|
      format.html { redirect_to quickcheckers_url, notice: 'Quickchecker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quickchecker
      @quickchecker = Quickchecker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quickchecker_params
      params.require(:quickchecker).permit(:url1, :url2, :url3, :info, :file)
    end
end

app/helpers/quickcheckers_helper.rb
module QuickcheckersHelper
end

app/views/quickcheckers/_form.html.erb
<div class="center-box">
  <div class="row-fluid">
    <div class="span6 offset3">

        <%= form_for(quickchecker) do |f| %>
          <% if quickchecker.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(quickchecker.errors.count, "error") %> prohibited this quickchecker from being saved:</h2>
        
              <ul>
              <% quickchecker.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        
          <%= f.text_field :url1, placeholder: "Insert the 1st website link (Required)", required: true, class: "form-control" %> 
          <%= f.text_field :url2, placeholder: "Insert the 2nd website link ", class: "form-control" %> 
          <%= f.text_field :url3, placeholder: "Insert the 3rd website link", class: "form-control" %> 
        
          <div class="actions" align="center">
            <%= f.submit "Submit", class: "btn btn-success" %>
            <%= link_to 'Back', :back, class:'btn btn-danger' %>
            <%= link_to 'Home', root_path, class:'btn btn-primary' %>
          </div>
        <% end %>
  </div>
  </div>  
</div>

app/views/quickcheckers/edit.html.erb
<h1>Editing Quickchecker</h1>

<%= render 'form', quickchecker: @quickchecker %>

<%= link_to 'Show', @quickchecker %> |
<%= link_to 'Back', quickcheckers_path %>

app/views/quickcheckers/index.html.erb
<h3><span><%= notice %></h3><span>
</br>
<h1><span>List of Reports</span></h1>
<div class="tables-center">
    <table class="tables table-striped table-dark">
      <thead>
        <tr class="bg-primary">
          <th>Websites</th>
          <th></th>
          <th></th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @quickcheckers.each do |quickchecker| %>
          <tr>
            <td><%=quickchecker.url1%></br></br><%= quickchecker.url2%></br></br><%= quickchecker.url3%></td>
            <td><%= link_to 'Show', quickchecker, :class => 'btn btn-success' %></td>
            <td><%= link_to 'Destroy', quickchecker, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>    

<div class="actions" align="center">
    <%= link_to 'New Analysis', new_quickchecker_path, class: "btn btn-primary"%>
    <%= link_to 'Back', root_path, class:'btn btn-danger' %>
    <%= link_to 'Home', root_path, class:'btn btn-success' %>
</div>

app/views/quickcheckers/new.html.erb
<h3><span><%= notice %></h3><span>
<br><br>
<h1><span>New Analysis</span></h1>


<%= render 'form', quickchecker: @quickchecker %>

app/views/quickcheckers/show.html.erb
<h3><span><%= notice %></h3><span>
</br>
<h1><span>Report No. <%= @quickchecker.id%> </span></h1>
<% require 'json' %>

 <div class="tables-center"> 
 	<% info = JSON.parse(@quickchecker.info)%>
 	<% count = info.count/4%>
	<% for i in 1..count do %>
		<table class="tables table-striped">
			<% if i==1 %>
				<% @url = @quickchecker.url1%>
				<% @total =  info[1]%>
				<% $t1 =  @total%>
				<% @errors = info[2]%>
				<% @warnings = info[3]%>
			<% end %>
			<% if i==2 %>
				<% @url = @quickchecker.url2%>
				<% @total =  info[5]%>
				<% @errors = info[6]%>
				<% @warnings = info[7]%>
			<% end %>
			<% if i==3 %>
				<% @url = @quickchecker.url3%>
				<% @total =  info[9]%>
				<% @errors = info[10]%>
				<% @warnings = info[11]%>
			<% end %>
			<thead>
				<tr class="bg-primary">
					<th><%= @url %></th>
				<th colspan="10"></th>
				</tr>
				<tr>
					<td>Issues</td>
				<td><%= @errors %></td>
				</tr>
				<tr>
					<td>Warnings</td>
					<td><%= @warnings %></td>
				</tr>
				<tr>
					<td>Total Error</td>
					<td><%= @total %></td>
				</tr>
			</thead>
		</table>
		
		<div class="actions" align="center">
			<%= link_to 'View full report', report_path(:url => @file_name, :pos => i)	, class:'btn btn-success' %>
		</div>
	<%end%>    
</div></br>
	<div class="actions" align="center">
        <%= link_to 'Compare all websites', compare_path(:url => @file_name,:count => count), class:'btn btn-warning' %>
        <%= link_to 'Back', quickcheckers_path, class:'btn btn-danger' %>
        <%= link_to 'Home', root_path, class:'btn btn-primary' %>
  	</div>